[mgr]
show_hidden = true

[opener]
open = [
    { run = 'xdg-open $@', desc = "Open" }
]
edit = [
	{ run = '$EDITOR "$@"', block = true, for = "unix" },
	{ run = "%EDITOR% %*",  block = true, for = "windows" },
]
