# Windows overrides — link.ps1 puts this at %APPDATA%/alacritty/alacritty.toml
[general]
import = ["~/.config/alacritty/alacritty.toml"]

[font]
normal = { family = "Iosevka NFM Medium", style = "Regular" }
bold = { family = "Iosevka NFM SemiBold", style = "Regular" }
italic = { family = "Iosevka NFM Medium Obl", style = "Regular" }
bold_italic = { family = "Iosevka NFM SemiBold Obl", style = "Regular" }

[terminal.shell]
program = "powershell.exe"
args = ["-NoLogo"]

[[keyboard.bindings]]
key = "C"
mods = "Control"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Control"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
chars = "\u0003"
